version: "3.8"
services:
  backend:
    image: "crudmax/springboot-react-fullstack:5.7.2023.19.4.36"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev