version: "3.8"
services:
  backend:
    image: "crudmax/springboot-react-fullstack:13.6.2023.2.17.54"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev