version: "3.8"
services:
  backend:
    image: "crudmax/springboot-react-fullstack:15.6.2023.17.3.31"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev