version: "3.8"
services:
  backend:
    image: "crudmax/springboot-react-fullstack:27.6.2023.15.5.36"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev