version: "3.8"
services:
  backend:
    image: "crudmax/springboot-react-fullstack:20.6.2023.18.39.29"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev