version: "3.8"
services:
  backend:
    image: "crudmax/springboot-react-fullstack:4.7.2023.17.32.1"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev