version: "3.8"
services:
  backend:
    image: "crudmax/springboot-react-fullstack:12.6.2023.19.38.20"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev