version: "3.8"
services:
  backend:
    image: "crudmax/springboot-react-fullstack:26.6.2023.20.55.49"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev