version: "3.8"
services:
  backend:
    image: "crudmax/springboot-react-fullstack:21.6.2023.16.21.50"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev